build: false
branches:
  only:
    - master
    - develop
environment:
    PYTHON: "C:\\Python27"
    PYTHON_VERSION: "2.7.8"
    PYTHON_ARCH: "32"

    CONAN_UPLOAD: 1
    CONAN_REFERENCE: "small3d/1.1.0"
    CONAN_USERNAME: "coding3d"
    CONAN_CHANNEL: "testing"
    CONAN_TOTAL_PAGES: 2

    matrix:
        - CONAN_CURRENT_PAGE: 1
        - CONAN_CURRENT_PAGE: 2

install:
  - set PATH=%PATH%;%PYTHON%/Scripts/
  - pip.exe install conan_package_tools
  - conan user

test_script:
  - C:\Python27\python build.py
